# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-14 01:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CookingTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.IntegerField(default=0, verbose_name='hours')),
                ('minutes', models.IntegerField(default=0, verbose_name='minutes')),
            ],
            options={
                'verbose_name': 'cooking time',
                'verbose_name_plural': 'cooking time',
            },
        ),
        migrations.CreateModel(
            name='Cuisine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuisine', models.CharField(blank=True, choices=[('asian', 'Asian'), ('caribbean', 'Caribbean'), ('chinese', 'Chinese'), ('french', 'French'), ('russian', 'Russian'), ('indian', 'Indian'), ('italian', 'Italian'), ('mexican', 'Mexican'), ('mediterranean', 'Mediterranean')], max_length=50, null=True, verbose_name='Cuisine')),
            ],
            options={
                'verbose_name': 'Cuisine',
                'verbose_name_plural': 'Cuisine',
            },
        ),
        migrations.CreateModel(
            name='Difficulty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty', models.CharField(blank=True, choices=[('simple', 'Simple'), ('medium', 'Medium'), ('difficult', 'Difficult')], max_length=20, null=True, verbose_name='Difficulty')),
            ],
            options={
                'verbose_name': 'Difficulty',
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(blank=True, max_length=10, null=True, verbose_name='Quantity')),
                ('unit', models.CharField(blank=True, choices=[('cup', 'cup'), ('kg', 'kg'), ('liter', 'liter'), ('gram', 'gram'), ('tspoon', 'tspoon'), ('spoon', 'spoon')], max_length=20, null=True, verbose_name='Unit')),
                ('ingredient', models.CharField(max_length=100, verbose_name='Ingredient')),
                ('note', models.CharField(blank=True, max_length=200, null=True, verbose_name='Note')),
            ],
            options={
                'verbose_name': 'Ingredient',
                'verbose_name_plural': 'Ingredients',
            },
        ),
        migrations.CreateModel(
            name='MealType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mealtype', models.CharField(blank=True, choices=[('breakfast', 'Breakfast'), ('dinner', 'Dinner'), ('quick', 'Quick & Easy'), ('soups', 'Soups'), ('desserts', 'Desserts'), ('fish', 'Fish'), ('grill', 'Grill'), ('kids', 'Kids'), ('chicken', 'Chicken'), (('meat',), 'Meat'), ('salads', 'Salads'), ('veggie', 'Veggie'), ('seafood', 'Seafood')], max_length=50, null=True, verbose_name='Meal type')),
            ],
            options={
                'verbose_name': 'Mealtype',
                'verbose_name_plural': 'Mealtypes',
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='Title')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='media/cooks/img')),
                ('summary', models.TextField(blank=True, null=True, verbose_name='Summary')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('portions', models.IntegerField(blank=True, null=True, verbose_name='Portions')),
                ('publish_date', models.DateTimeField(verbose_name='publish_date')),
            ],
            options={
                'verbose_name': 'Recipe',
                'verbose_name_plural': 'Recipes',
                'ordering': ('publish_date',),
            },
        ),
        migrations.CreateModel(
            name='WorkingTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.IntegerField(default=0, verbose_name='hours')),
                ('minutes', models.IntegerField(default=0, verbose_name='minutes')),
                ('recipe', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='working_hours', to='cooks.Recipe', verbose_name='Recipe')),
            ],
            options={
                'verbose_name': 'working hour',
                'verbose_name_plural': 'working hour',
            },
        ),
        migrations.AddField(
            model_name='mealtype',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_type', to='cooks.Recipe', verbose_name='Recipe'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='cooks.Recipe', verbose_name='Recipe'),
        ),
        migrations.AddField(
            model_name='difficulty',
            name='recipe',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='difficulty', to='cooks.Recipe', verbose_name='Recipe'),
        ),
        migrations.AddField(
            model_name='cuisine',
            name='recipe',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cuisine', to='cooks.Recipe', verbose_name='Recipe'),
        ),
        migrations.AddField(
            model_name='cookingtime',
            name='recipe',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cooking_time', to='cooks.Recipe', verbose_name='Recipe'),
        ),
    ]
