# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-04 04:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Difficulty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty', models.IntegerField(blank=True, choices=[(1, 'simple'), (2, 'medium'), (3, 'difficult')], null=True, verbose_name='Difficulty')),
            ],
            options={
                'verbose_name': 'difficulty',
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(blank=True, max_length=10, null=True, verbose_name='Quantity')),
                ('unit', models.IntegerField(blank=True, choices=[(4, 'cup'), (2, 'kg'), (1, 'liter'), (3, 'gram'), (5, 'tspoon'), (6, 'spoon')], null=True, verbose_name='Unit')),
                ('ingredient', models.CharField(max_length=100, verbose_name='Ingredient')),
                ('note', models.CharField(blank=True, max_length=200, null=True, verbose_name='Note')),
            ],
            options={
                'verbose_name': 'Ingredient',
                'verbose_name_plural': 'Ingredients',
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Title')),
                ('photo', models.ImageField(upload_to='cooks')),
                ('summary', models.TextField(blank=True, null=True, verbose_name='Summary')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('portions', models.IntegerField(blank=True, null=True, verbose_name='Portions')),
                ('publish_date', models.DateTimeField(verbose_name='publish_date')),
            ],
            options={
                'verbose_name': 'Recipe',
                'verbose_name_plural': 'Recipes',
                'ordering': ('publish_date',),
            },
        ),
        migrations.AddField(
            model_name='ingredient',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='cooks.Recipe', verbose_name='Recipe'),
        ),
        migrations.AddField(
            model_name='difficulty',
            name='recipe',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='difficulty', to='cooks.Recipe', verbose_name='Recipe'),
        ),
    ]
