# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-04 06:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='difficulty',
            name='difficulty',
            field=models.CharField(blank=True, choices=[('simple', 'simple'), ('medium', 'medium'), ('difficult', 'difficult')], max_length=20, null=True, verbose_name='Difficulty'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(blank=True, choices=[('cup', 'cup'), ('kg', 'kg'), ('liter', 'liter'), ('gram', 'gram'), ('tspoon', 'tspoon'), ('spoon', 'spoon')], max_length=20, null=True, verbose_name='Unit'),
        ),
    ]
