# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-14 17:40
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cooks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favourite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('favorer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoring', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Favorite Recipe',
                'verbose_name_plural': 'Fvorite Recipes',
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likes_count', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Likes',
                'verbose_name_plural': 'Likes',
            },
        ),
        migrations.AddField(
            model_name='recipe',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='like',
            name='recipe',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='like', to='cooks.Recipe', verbose_name='Recipe'),
        ),
        migrations.AddField(
            model_name='favourite',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite', to='cooks.Recipe', verbose_name='Recipe'),
        ),
        migrations.AlterUniqueTogether(
            name='favourite',
            unique_together=set([('recipe', 'favorer')]),
        ),
    ]
