# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-04 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooks', '0002_auto_20170504_0905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='photo',
            field=models.ImageField(upload_to='static/cooks'),
        ),
    ]
