# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-14 21:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cooks', '0002_auto_20170514_2040'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Favourite',
            new_name='Favorite',
        ),
    ]
