# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-04 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooks', '0003_auto_20170504_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='photo',
            field=models.ImageField(upload_to='cooks/static/cooks/img'),
        ),
    ]
