# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-17 12:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cooks', '0003_auto_20170515_0009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='likes_count',
        ),
        migrations.AddField(
            model_name='like',
            name='liker',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='liking', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='favorite',
            name='favorer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='favoring', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='like',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like', to='cooks.Recipe', verbose_name='Recipe'),
        ),
    ]
