# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-04 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooks', '0004_auto_20170504_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='photo',
            field=models.ImageField(upload_to='media/cooks/img'),
        ),
    ]
