# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-17 12:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cooks', '0004_auto_20170517_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='favorer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoring', to=settings.AUTH_USER_MODEL),
        ),
    ]
