# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-27 08:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooks', '0005_auto_20170517_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealtype',
            name='mealtype',
            field=models.CharField(blank=True, choices=[('breakfast', 'Breakfast'), ('dinner', 'Dinner'), ('quick', 'Quick & Easy'), ('soups', 'Soups'), ('desserts', 'Desserts'), ('fish', 'Fish'), ('grill', 'Grill'), ('kids', 'Kids'), ('chicken', 'Chicken'), ('meat', 'Meat'), ('salads', 'Salads'), ('veggie', 'Veggie'), ('seafood', 'Seafood')], max_length=50, null=True, verbose_name='Meal type'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='title',
            field=models.CharField(default=None, max_length=200, unique=True, verbose_name='Title'),
            preserve_default=False,
        ),
    ]
