# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-27 17:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_auto_20170514_0429'),
        ('cooks', '0009_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='comment',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='comments.Comment', verbose_name='Comment'),
            preserve_default=False,
        ),
    ]
