# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 16:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooks', '0011_auto_20170527_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cookingtime',
            name='hours',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='hours'),
        ),
        migrations.AlterField(
            model_name='cookingtime',
            name='minutes',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='minutes'),
        ),
    ]
